from dataclasses import dataclass
from math import sqrt


GRAVITY = 9.81


@dataclass(frozen=True)
class BreachResult:
    method: str
    average_breach_width_m: float
    formation_time_hr: float
    side_slope_h_to_v: float
    peak_discharge_m3s: float | None
    notes: tuple[str, ...]


def _failure_factor(failure_mode: str) -> float:
    return 1.4 if failure_mode.lower().startswith("overtopping") else 1.0


def _side_slope(failure_mode: str) -> float:
    return 1.4 if failure_mode.lower().startswith("overtopping") else 0.9


def froehlich_1995(
    reservoir_volume_m3: float,
    breach_height_m: float,
    water_height_above_breach_m: float,
    failure_mode: str,
) -> BreachResult:
    """Froehlich 1995 empirical breach width/time and peak discharge equations."""
    k0 = _failure_factor(failure_mode)
    width = 0.1803 * k0 * reservoir_volume_m3**0.32 * breach_height_m**0.19
    formation_time = 0.00254 * reservoir_volume_m3**0.53 * breach_height_m**-0.90
    peak = 0.607 * reservoir_volume_m3**0.295 * water_height_above_breach_m**1.24
    return BreachResult(
        method="Froehlich 1995",
        average_breach_width_m=width,
        formation_time_hr=formation_time,
        side_slope_h_to_v=_side_slope(failure_mode),
        peak_discharge_m3s=peak,
        notes=(
            "Useful as a first empirical estimate for embankment dam failures.",
            "For moraine dams, treat this as a rough comparison rather than a perfect fit.",
        ),
    )


def froehlich_2008(
    reservoir_volume_m3: float,
    breach_height_m: float,
    failure_mode: str,
) -> BreachResult:
    """Froehlich 2008 updated breach width/time equations."""
    k0 = _failure_factor(failure_mode)
    width = 0.27 * k0 * reservoir_volume_m3**0.32 * breach_height_m**0.04
    formation_time_seconds = 63.2 * sqrt(reservoir_volume_m3 / (GRAVITY * breach_height_m**2))
    formation_time = formation_time_seconds / 3600
    return BreachResult(
        method="Froehlich 2008",
        average_breach_width_m=width,
        formation_time_hr=formation_time,
        side_slope_h_to_v=_side_slope(failure_mode),
        peak_discharge_m3s=None,
        notes=(
            "Provides breach width and formation time; peak discharge is generated by the hydrograph module.",
            "Best used for constructed embankment dams within the original data range.",
        ),
    )


def macdonald_langridge_monopolis_1984(
    reservoir_volume_m3: float,
    water_height_above_breach_m: float,
    breach_height_m: float,
    side_slope_h_to_v: float,
) -> BreachResult:
    """Simplified MacDonald & Langridge-Monopolis breach estimates."""
    eroded_volume = 0.00348 * (reservoir_volume_m3 * water_height_above_breach_m) ** 0.852
    formation_time = 0.0179 * eroded_volume**0.364
    width = max(eroded_volume / max(breach_height_m**2 * (side_slope_h_to_v + 1.0), 1e-6), 0.1)
    peak = 1.154 * (reservoir_volume_m3 * water_height_above_breach_m) ** 0.412
    return BreachResult(
        method="MacDonald & Langridge-Monopolis 1984",
        average_breach_width_m=width,
        formation_time_hr=formation_time,
        side_slope_h_to_v=side_slope_h_to_v,
        peak_discharge_m3s=peak,
        notes=(
            "Useful for erosion-type breaches and conservative comparison.",
            "This prototype uses a simplified average-width estimate from eroded breach volume.",
        ),
    )


def run_breach_method(
    method: str,
    reservoir_volume_m3: float,
    breach_height_m: float,
    water_height_above_breach_m: float,
    failure_mode: str,
    side_slope_h_to_v: float,
) -> BreachResult:
    if reservoir_volume_m3 <= 0 or breach_height_m <= 0 or water_height_above_breach_m <= 0:
        raise ValueError("Reservoir volume, breach height, and water height must be greater than zero.")

    if method == "Froehlich 1995":
        return froehlich_1995(reservoir_volume_m3, breach_height_m, water_height_above_breach_m, failure_mode)
    if method == "Froehlich 2008":
        return froehlich_2008(reservoir_volume_m3, breach_height_m, failure_mode)
    if method == "MacDonald & Langridge-Monopolis 1984":
        return macdonald_langridge_monopolis_1984(
            reservoir_volume_m3, water_height_above_breach_m, breach_height_m, side_slope_h_to_v
        )
    raise ValueError(f"Unknown breach method: {method}")
